<?php

namespace AppBundle\Repository;

/**
 * ApplicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationsRepository extends \Doctrine\ORM\EntityRepository
{
}
